line-length = 100
target-version = "py310"

[lint]
select = [
  "E",  # pycodestyle
  "F",  # pyflakes
  "I",  # isort
  "UP", # pyupgrade
  "B",  # bugbear
]
ignore = [
]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false


