name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - name: Install deps
        run: |
          uv venv
          uv pip install -e .[dev]
      - name: Lint
        run: uv run ruff check .
      - name: Type-check
        run: uv run mypy src
      - name: Tests
        run: uv run pytest -q --maxfail=1


